# @port = 3040

### add device
POST {{host}}/devices
content-type: application/json

{
  "name": "light 4",
  "user": "6427fe93dab74de19ff58d6a",
  "state": true
}

### get all devices
GET {{host}}/devices

### get device 1
GET {{host}}/devices/6427ffc40934446e9b370cf1

### get device 2
GET {{host}}/devices/6428028f8341127c6d280f7e

### update device
PATCH {{host}}/devices/64282e65df56c9885a2d6951
content-type: application/json

{
  "name": "fan 3",
  "state": false
}

### delete device
DELETE  {{host}}/devices/64282477fa7781f1d70af9bd

