# @port = 3040

# @name create_device
POST {{host}}/devices
content-type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "light 9",
  "user": "642fcee2010a2e856a13ae89",
  "state": true
}

### get all devices
GET {{host}}/devices

### get device 1
GET {{host}}/devices/642fb922355a3a42c81d809d

### get device 2
GET {{host}}/devices/6428028f8341127c6d280f7e

### update device
PATCH {{host}}/devices/64319c471827dbe612893c1f
content-type: application/json

{
  "name": "AC 3",
  "state": false
}

### delete device
DELETE  {{host}}/devices/64282477fa7781f1d70af9bd

