### Register
POST http://localhost:3052/api/auth/register
content-type: application/json

{
  "name": "user2",
  "email": "user2@gmail.com",
  "password": "password"
}

### Login
POST http://localhost:3052/api/auth/login
content-type: application/json

{
  "email": "user2@gmail.com",
  "password": "password"
}
