### add device
POST http://localhost:3052/api/scenarios
content-type: application/json

{
  "name": "Good night",
  "user": "6427fe85dab74de19ff58d67",
  "actions": [
    {
      "device": "6428028f8341127c6d280f7e",
      "state": true
    }
  ],
  "isFavorite": false 
}

### get scenario
GET http://localhost:3052/api/scenarios/642a69e9d0c4decb4e99a098


### get all scenarios
GET http://localhost:3052/api/scenarios


### update scenario
PATCH http://localhost:3052/api/scenarios/642a69e9d0c4decb4e99a098
content-type: application/json

{
  "name": "Go out",
  "isFavorite": false
}

### delete scenario
DELETE http://localhost:3052/api/scenarios/642bf3be9c4f32cac0bc0395
