### add device
POST {{host}}/scenarios
content-type: application/json

{
  "name": "Good night",
  "user": "6427fe85dab74de19ff58d67",
  "actions": [
    {
      "device": "6428028f8341127c6d280f7e",
      "state": true
    }
  ],
  "isFavorite": false 
}

### get scenario
GET {{host}}/scenarios/642bf3be9c4f32cac0bc0395


### get all scenarios
GET {{host}}/scenarios


### update scenario
PATCH {{host}}/scenarios/642bf335062b4943e4b731d1
content-type: application/json

{
  "name": "Go out",
  "isFavorite": false
}

### delete scenario
DELETE {{host}}/scenarios/642bf3be9c4f32cac0bc0395
