version: '3.8'

services:
  database:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: smartplug_dev
  
  mqtt_broker:
    image: eclipse-mosquitto
    ports:
      - 1884:1883
      - 9002:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mqtt_data:/mosquitto/data/


volumes:
  data:
  mqtt_data:
