version: '3.8'

services:
  database:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongod.conf:/etc/mongod.conf
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: smartplug_dev
    networks:
      - smartplug

  backend: 
    build: ./  
    ports:
      - 3000:3000
    volumes:
      - ./:/app/backend
      - /app/backend/node_modules
    networks:
      - smartplug
    depends_on:
      - database


networks:
  smartplug:

volumes:
  data:
  mqtt_data:
